package io.github.abarhub.vfs.core.plugin.audit;

public enum VFS4JAuditOperation {
    NEW_INPUT_STREAM, NEW_OUTPUT_STREAM, NEW_READER, NEW_WRITER, NEW_BYTE_CHANNEL, NEW_DIRECTORY_STREAM,

    CREATE_FILE, CREATE_DIRECTORY, CREATE_DIRECTORIES, DELETE, DELETE_IF_EXISTS, CREATE_LINK, CREATE_SYMBOLIC_LINK, COPY,
    MOVE, WRITE,

    SET_ATTRIBUTE, SET_LAST_MODIFIED_TIME, SET_OWNER, SET_POSIX_FILE_PERMISSIONS, GET_ATTRIBUTE, GET_FILE_ATTRIBUTE_VIEW,
    GET_LAST_MODIFIED_TIME, GET_OWNER, GET_POSIX_FILE_PERMISSIONS, IS_EXECUTABLE, IS_READABLE, IS_HIDDEN,
    IS_WRITABLE, READ_ATTRIBUTES,

    LIST, WALK, FIND,

    EXISTS, IS_DIRECTORY, IS_REGULAR_FILE, IS_SAME_FILE, IS_SYMBOLIC_LINK, LINES, NOT_EXISTS,
    READ_ALL_BYTES, READ_ALL_LINES, SIZE

}
